# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

barrdglupd_c <- function(A, B, lambda, beta0) {
    .Call('bar_barrdglupd_c', PACKAGE = 'bar', A, B, lambda, beta0)
}

barrdghupd_c <- function(X, B, lambda, weight) {
    .Call('bar_barrdghupd_c', PACKAGE = 'bar', X, B, lambda, weight)
}

barridge_c <- function(A, B, n, p, xiv, lambdav, abstol, stand) {
    .Call('bar_barridge_c', PACKAGE = 'bar', A, B, n, p, xiv, lambdav, abstol, stand)
}

barcd_c <- function(A, B, n, p, xiv, lambdav, abstol) {
    .Call('bar_barcd_c', PACKAGE = 'bar', A, B, n, p, xiv, lambdav, abstol)
}

barcv_c <- function(A, B, trainL, testL, n, p, xiv, lambdav, nfold, method, abstol, stand) {
    .Call('bar_barcv_c', PACKAGE = 'bar', A, B, trainL, testL, n, p, xiv, lambdav, nfold, method, abstol, stand)
}

zbar_c <- function(zmat, Cv, s) {
    .Call('bar_zbar_c', PACKAGE = 'bar', zmat, Cv, s)
}

zbarsum_c <- function(zmat, Cv, t) {
    .Call('bar_zbarsum_c', PACKAGE = 'bar', zmat, Cv, t)
}

V_c <- function(zmat, Cv) {
    .Call('bar_V_c', PACKAGE = 'bar', zmat, Cv)
}

Omega_c <- function(zmat, tlist, Cv) {
    .Call('bar_Omega_c', PACKAGE = 'bar', zmat, tlist, Cv)
}

P_c <- function(zmat, tlist, olist, Cv) {
    .Call('bar_P_c', PACKAGE = 'bar', zmat, tlist, olist, Cv)
}

reggenint_c <- function(Cv, Zmat, olist, tlist, mind) {
    .Call('bar_reggenint_c', PACKAGE = 'bar', Cv, Zmat, olist, tlist, mind)
}

bar_rcpparma_hello_world <- function() {
    .Call('bar_bar_rcpparma_hello_world', PACKAGE = 'bar')
}

rcpparma_outerproduct <- function(x) {
    .Call('bar_rcpparma_outerproduct', PACKAGE = 'bar', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('bar_rcpparma_innerproduct', PACKAGE = 'bar', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('bar_rcpparma_bothproducts', PACKAGE = 'bar', x)
}

ridreg_c <- function(A, B, binital, lambda, weight, abstol) {
    .Call('bar_ridreg_c', PACKAGE = 'bar', A, B, binital, lambda, weight, abstol)
}

ridreg0_c <- function(X, Y, binital, lambda, weight, abstol) {
    .Call('bar_ridreg0_c', PACKAGE = 'bar', X, Y, binital, lambda, weight, abstol)
}

ridregi_c <- function(X, Y, lambda, weight, abstol) {
    .Call('bar_ridregi_c', PACKAGE = 'bar', X, Y, lambda, weight, abstol)
}

ridreg1_c <- function(X, Y, lambda, weight, abstol) {
    .Call('bar_ridreg1_c', PACKAGE = 'bar', X, Y, lambda, weight, abstol)
}

ridreg2_c <- function(A, B, lambda, weight, abstol) {
    .Call('bar_ridreg2_c', PACKAGE = 'bar', A, B, lambda, weight, abstol)
}

ridreg3_c <- function(A, B, lambda, weight, abstol) {
    .Call('bar_ridreg3_c', PACKAGE = 'bar', A, B, lambda, weight, abstol)
}

ridreg4_c <- function(A, B, lambda, weight, abstol) {
    .Call('bar_ridreg4_c', PACKAGE = 'bar', A, B, lambda, weight, abstol)
}

ridregM1_c <- function(A, B, lambda, weight, abstol) {
    .Call('bar_ridregM1_c', PACKAGE = 'bar', A, B, lambda, weight, abstol)
}

ridregM2_c <- function(A, B, lambda, weight, r, abstol) {
    .Call('bar_ridregM2_c', PACKAGE = 'bar', A, B, lambda, weight, r, abstol)
}

ridregM3_c <- function(X, B, lambda, weight, r, abstol) {
    .Call('bar_ridregM3_c', PACKAGE = 'bar', X, B, lambda, weight, r, abstol)
}

ridregM4_c <- function(X, B, lambda, weight, r, abstol) {
    .Call('bar_ridregM4_c', PACKAGE = 'bar', X, B, lambda, weight, r, abstol)
}

test1 <- function(A, t) {
    .Call('bar_test1', PACKAGE = 'bar', A, t)
}

test2 <- function(A, t) {
    .Call('bar_test2', PACKAGE = 'bar', A, t)
}

sfun_c <- function(z, lambda) {
    .Call('bar_sfun_c', PACKAGE = 'bar', z, lambda)
}

scadupdate_c <- function(z, lambda, gam, wjj) {
    .Call('bar_scadupdate_c', PACKAGE = 'bar', z, lambda, gam, wjj)
}

elnetupdate_c <- function(z, lambda, alpha, wjj) {
    .Call('bar_elnetupdate_c', PACKAGE = 'bar', z, lambda, alpha, wjj)
}

penreg_c <- function(A, B, n, p, lambdav, weight, alpha, gamma, method, abstol) {
    .Call('bar_penreg_c', PACKAGE = 'bar', A, B, n, p, lambdav, weight, alpha, gamma, method, abstol)
}

pencv_c <- function(A, B, trainL, testL, n, p, lambdav, weight, nfold, alpha, gamma, method, abstol) {
    .Call('bar_pencv_c', PACKAGE = 'bar', A, B, trainL, testL, n, p, lambdav, weight, nfold, alpha, gamma, method, abstol)
}

test <- function(a, b) {
    .Call('bar_test', PACKAGE = 'bar', a, b)
}

rss_c <- function(A, B, beta) {
    .Call('bar_rss_c', PACKAGE = 'bar', A, B, beta)
}

rssf_c <- function(A, B, beta, tss) {
    .Call('bar_rssf_c', PACKAGE = 'bar', A, B, beta, tss)
}

standard_c <- function(A, B, n) {
    .Call('bar_standard_c', PACKAGE = 'bar', A, B, n)
}

